### ISSUE TITLE
Support multiple sets of coordinates for Clean custom area

### ISSUE THREAD

**Issue by dahmz** [DeebotUniverse/Deebot-4-Home-Assistant#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

In the Ecovacs app I can add multiple custom areas to clean at once. When I do this I see in the logs for Deebot-4-Home-Assistant something like this:
`2022-07-19 11:30:01 DEBUG (MainThread) [deebot_client.commands.clean] Last custom area values (x1,y1,x2,y2): -1924,3777,527,-588;-2915,2588,-1860,-919;-4768,2579,-2860,1548;-4768,3621,-3768,2548;-6446,3580,-4727,1750;`

Where it lists all the sets of coordinates separated by semicolons. If I try to put this same string into the custom_area command it only runs on the first set of coordinates.

eg:
```
sequence:
  - service: vacuum.send_command
    target:
      entity_id: vacuum.scruffy
    data:
      command: custom_area
      params:
        coordinates: '-1924,3777,527,-588;-2915,2588,-1860,-919;-4768,2579,-2860,1548;-4768,3621,-3768,2548;-6446,3580,-4727,1750;'
```

I would love to be able to pass something like this to allow multiple sets if needed.

### Suggested solution

Add support for multiple sets of coordinates in the params for custom_area command. Either by semicolons, or a list of coordinates in the params.
