### ISSUE TITLE
Deebot T9+ starts but does not proceed to any rooms

### ISSUE THREAD

**Issue by AndrewD79** [DeebotUniverse/Deebot-4-Home-Assistant#243]
### Question

I've setup the following script to run from one of the shortcut buttons (using the Simple UI example).
When it runs, the Deebot moves off the dock but just sits there.
If I check the Ecovancs app, it shows that the correct rooms should be getting cleaned, but the deebot does not move.
NB: originally I didn't have the vacuum.cheryl > type: clean section, just the vacuum.send_command section. Aside from the deebot announcing both actions, including/removing the 'type:clean' section makes no difference.
Also this was adapted from one of the examples so there are some leftover (but should be irrelevant) parts, eg: queue.
I can't for the life of me get the advanced UI example to work, but thats another story - one step at a time

```
alias: CLEAN_LIVINGROOM
sequence:
  - device_id: c22572de834a51e5eead97577fad77a3
    domain: vacuum
    entity_id: vacuum.cheryl
    type: clean
    enabled: false                << *edit - only additional difference in my new script
  - alias: Send cleaning job to vacuum
    service: vacuum.send_command
    data:
      entity_id: "{{ vacuum_bot }}"
      command: spot_area
      params:
        rooms: 0,5
        cleanings: 1
description: Start a deebot cleaning task
variables:
  queue: input_text.deebot_cheryl_queue
  vacuum_bot: vacuum.cheryl
mode: restart
icon: mdi:sofa-outline
```

 UPDATE 
Shortly after this I noticed that my Deebot was now also having the same problem when using the Deebot phone app - it would not proceed to rooms. I deleted the map from the app and tried to get it to re-map the house. This also didn't work. I had to factory reset the Deebot completely and get it to re-map the house.
After that, my scripts were working fine.
The issue definitely started (or was first noticed) when trying to run the Deebot from this HASS script, but it is unclear if the actual issue was HASS, Script, or Deebot related.

Also note, my new script is running fine and does multiple rooms. the only difference is the 'enabled: false" line, as shown above.

**Comment by jumpinf00l** [comment]
I had the same issue also with a T9+, only a single room number could be specified at a time in vacuum.send_command. The vacuum moves off the dock and sits stationary with the brushes and motor running

**Comment by edenhaus** [comment]
@AndrewD79  Can you please try to remove the first action completely? It should not be required and makes only problems probably.

@jumpinf00l This happens if you send wrong room ids to the bot. At least this happens on my 950

**Comment by jumpinf00l** [comment]
I stand corrected! Below works perfectly, I'm sure it didn't work before but thanks @edenhaus for the reply

```
service: vacuum.send_command
data:
  entity_id: vacuum.deebot_t9_plus
  command: spot_area
  params:
    rooms: 6,8
    cleanings: 1
```
