### ISSUE TITLE
Does it support starting automatic dust collection function or calling manual dust collection?

### ISSUE THREAD

**Issue by soulxyz** [DeebotUniverse/Deebot-4-Home-Assistant#289]
### Question

I have a DEEBOT X1 OMNI. And today I try the Deebot-4-Home-Assistant in home assistant. To my delight, I have made clear the specific functions except "_button. di_bao_relocate_", but I found that there is no automatic dust collection switch or manual dust collection button. How can I add new functions?

**Comment by edenhaus** [comment]
This component does not support these features yet. Please feel free to add it 😊

**Comment by soulxyz** [comment]
I just found that [this project](https://github.com/mrbungle64/ecovacs-deebot.js#092-alpha) seems to be supporting automatic dust collection. I will try to add it, but my level may be limited. I would appreciate it if you could support automatic dust collection.
_https://github.com/mrbungle64/ecovacs-deebot.js#092-alpha
Some improvements for
auto empty station
dnd mode
cleaning logs
mopping modes_

**Comment by Yterz** [comment]
You can do both with the service ```vacuum.send_command```

For the manual dust collection button, in a script it would be :
```
service: vacuum.send_command
data:
  command: setAutoEmpty
  params:
    act: start
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
```

I put mine directly in the custom vacuum-card config that way :
```
shortcuts:
  - service: vacuum.send_command
    service_data:
      command: setAutoEmpty
      params:
        act: start
      entity_id: vacuum.YOUR_ROBOT_NAME
    icon: mdi:delete-empty
```


For the setting Auto-Empty On/Off, in a script it would be :
```
service: vacuum.send_command
data:
  command: setAutoEmpty
  params:
    enable: [1 or 0]
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
```

If you want to add that setting to the repo, you would also be interested by getAutoEmpty, to read the curent state.

Source : [DeebotUniverse/auto_empty](https://deebot.readthedocs.io/advanced/data_types/json/commands/auto_empty/)
