### ISSUE TITLE
How to set number of cleanings with custom coords?

### ISSUE THREAD

**Issue by migius** [DeebotUniverse/Deebot-4-Home-Assistant#295]
### Question

Is there any way to set 2 cleanings with "custom_area"? In the app is possible. 
I found this example:
```
service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: spot_area
  params:
    rooms: 10,14
    cleanings: 1
```
I try with something like this:

```
service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: custom_area
  params:
    coordinates: -1339,-1511,296,-2587
    cleanings: 2

```
but `cleanings: 2` apparently it doesn't work.
