### ISSUE TITLE
Deebot T8 AIVI - Send bot to position x,y?

### ISSUE THREAD

**Issue by fpdragon** [DeebotUniverse/Deebot-4-Home-Assistant#304]
### Question

Hello,

I am trying to switch from ioBroker to Home Assistant and currently I am having troubles in integration my Deebot T8 AIVI.
In ioBroker it was possible to send the bot to a defined position by executing “ecovacs-deebot.0.control.extended.goToPosition” and adding x and y coordinates.
I am searching for something similar in the integration [GitHub - DeebotUniverse/Deebot-4-Home-Assistant: Home Assistant integration for deebot vacuums](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant) but I have not found something like that.

I noticed that there is such a thing like “deebot_custom_command” and it may be possible to create such a move command here but here I am lost.

Maybe it is possible to reverse engineer the move command from ioBroker and add it to the project or workaround it with the custom command.

Hope someone can help since the move command would be essential for my setup.

Thanks.

**Comment by mrbungle64** [comment]
@fpdragon 

For the T8 AIVI you can use the following "deebot_custom_command":

```yaml
service: vacuum.send_command
data:
  command: clean_V2
  params:
    act: start
    content:
      type: customArea
      total: 0
      donotClean: 1
      count: 1
      value: "x,y,x,y"
target:
  device_id: device_id
```

**Comment by mrbungle64** [comment]
For T9, T10, X1 it should be:

```yaml
service: vacuum.send_command
data:
  command: clean_V2
  params:
    act: start
    content:
      type: mapPoint
      total: 0
      donotClean: 0
      count: 0
      value: "x,y"
target:
  device_id: device_id
```
