### ISSUE TITLE
Can we replaceroom number to variables ?

### ISSUE THREAD

**Issue by JeedHome44** [DeebotUniverse/Deebot-4-Home-Assistant#314]
### Question

Hello,

My Deebot X1 Omni change room number sometime.
So, when i do script to active robot cleaning 1 room, sometime, i need to change number.

I do an automation to attribute room number to variable with json.
It's ok. i have correct number in room variables.

My question: Can we write variable in room parametres like this:

# Clean Area
```
service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: spot_area
  params:
    rooms: {{ var.deebot_kitchen }}
    cleanings: 1
```

### Additional information

i test it but robot go only in room 0. Can you help me please ?
