### ISSUE TITLE
Room attributes are missing if the map is disabled

### ISSUE THREAD

**Issue by cpwc** [DeebotUniverse/Deebot-4-Home-Assistant#404]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Before upgrading I'm still able to see room details within the vacuum attributes. After upgrading the attributes are no longer available and it only shows `lastError` as part of the attributes.

### Diagnostics information

[deebot-ba5a346b4d1784b578223bef8dd1b11e-None-7e055a4ef67a0a4f5781f06315b557cb.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12286915/deebot-ba5a346b4d1784b578223bef8dd1b11e-None-7e055a4ef67a0a4f5781f06315b557cb.json.txt)

### Additional information

DEEBOT X1 OMNI

**Comment by eXitus01** [comment]
i cannot see also the floor after the update.

**Comment by redford-jones** [comment]
Yes, same issue here, but I think I may have resolved it.

Initially, after updating to the new new release, the attributes shown on my DEEBOT OZMO 920 Series were as follows:

```
fan_speed_list:
  - quiet
  - normal
  - max
  - max_plus
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: max_plus
last_error: 'NoError: Robot is operational (0)'
friendly_name: Diva
supported_features: 13180
```
I then went into the device, noticed that the new `Map` Controls entity was disabled. I enabled it via the entity properties dialog, disabled the old `Live Map` sensor and reloaded the integration. Attributes are now shown as:
```
fan_speed_list:
  - quiet
  - normal
  - max
  - max_plus
supported_features: 13180
battery_icon: mdi:battery-charging-100
friendly_name: Diva
rooms:
  default:
    - 1
    - 4
    - 0
    - 9
    - 11
  laundry: 6
  kitchen: 10
  living_room: 5
  sunroom: 7
  dining_room: 2
last_error: 'NoError: Robot is operational (0)'
battery_level: 100
fan_speed: max_plus
```
