### ISSUE TITLE
Can't get coordinate for cleaning Area

### ISSUE THREAD

**Issue by marcolino7** [DeebotUniverse/Deebot-4-Home-Assistant#432]
### Question

Hi,
I have Deebot T9 and integration installed via HACS and it is working fine.
I would like to check the coordinate for a custom_area, but both method described here: https://deebot.readthedocs.io/integrations/home-assistant/examples/commands/
seems do not work.
I setup Logs in this way:
```
logger:
  default: info
  logs:
    homeassistant.components.vacuum: debug
    custom_components.deebot: debug
    deebotozmo: debug
```
But I can't find coordinates in homeassistant.log, and listening for the event deebot_cleaning_job from dev tools, do not give me back any results.
Any help would be appreciated.

Thanks
