### ISSUE TITLE
Parameter "cleanings" is ignored

### ISSUE THREAD

**Issue by monotonus** [DeebotUniverse/Deebot-4-Home-Assistant#438]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have several rooms which I want to clean 2 times. So I set the parameter like in the documentation, but it's getting ignored and the rooms are cleaned only 1 time.

### Diagnostics information

```
badezimmerreinigung:
  alias: Badezimmerreinigung
  sequence:
  - data:
      command: spot_area
      entity_id: vacuum.detlef
      params:
        rooms: 3
        cleanings: 2
    service: vacuum.send_command
```

### Additional information

Home Assistant 2023.9.2

Deebot T9

**Comment by xxLexanixx** [comment]
Probier mal wenn du mode:single hinzufügst. So hab ich es bei mir eingestellt.
```
alias: Badezimmer reinigen
sequence:
  - service: vacuum.send_command
    data:
      command: spot_area
      params:
        rooms: 2
        cleanings: 1
    target:
      entity_id:
        - vacuum.hilde
mode: single
icon: mdi:shower
```
