### ISSUE TITLE
Message malformed: extra keys not allowed @ data['service']

### ISSUE THREAD

**Issue by Docjos** [DeebotUniverse/Deebot-4-Home-Assistant#507]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Hi everybody,

I am trying to install a command for my N8 Pro. It gives the following error: Message malformed: extra keys not allowed @ data['service']

This is also when copying the code from the [documentation](https://deebot.readthedocs.io/integrations/home-assistant/examples/commands/). I have changed the vacuum to my entity and haven't changed anything else except the room number. 

Anything Ihave to change? 
```
service: vacuum.send_command
target:
  entity_id: vacuum.stig_2
data:
  command: spot_area
  params:
    rooms: 10,14
    cleanings: 1
``` 
Thanks a lot!

### On which deebot vacuum you have the issue?

DEEBOT N8 PRO

### Which version of the Deebot component are you using?

3.1.1

### Which version of Home Assistant are you using?

2024.1.3

### What type of installation are you running?

Home Assistant OS

### Country

NL

### Continent

EU

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

-

**Comment by edenhaus** [comment]
```yaml
service: vacuum.send_command
data:
  command: spot_area
  params:
    rooms: 4,0
    cleanings: 1
target:
  entity_id: vacuum.susi
```

I can run the above snippet fine without any errors.
Make sure your bot is available and online.
Did you test the service call in the developer tools?
