### ISSUE TITLE
Migrating and merging this component with the Ecovacs core integration

### ISSUE THREAD

**Issue by edenhaus** [DeebotUniverse/Deebot-4-Home-Assistant#512]
I'm currently migrating this integration to the core to make it easier to use it and add the ability to translate it into all supported languages.
This issue is here to track the status.

This whole component will be included in HA 2024.2 except for the following things:
- The events `cleaning_job` and `custom_command`.
- The last cleaning and stats type sensors

### Migrations steps
1: Remove all [`Deebot 4 Home Assistant` config entries](https://my.home-assistant.io/redirect/integration/?domain=deebot)
2: Uninstall `Deebot 4 Home Assistant` via HACS
**3: Restart Home Assistant**
4: Setup the builtin `Ecovacs` integration

**If you have issues setting up the core integration, make sure no `deebot` folder exists under `[config dir]/custom_components` (Delete it if it exists) and restart  Home Assistant**

**Comment by scooper1** [comment]
the builtin Ecovacs integration is failing to authorise in the United Kingdom
working fine before migration 
feb beta 2

**Comment by edenhaus** [comment]
> the builtin Ecovacs integration is failing to authorise in the United Kingdom
> working fine before migration
> feb beta 2

@scooper1 Reported with https://github.com/home-assistant/core/issues/109336 and should be fixed with the next beta

**Comment by Ali229** [comment]
When I try to setup using integration it loads the setup for a long time and shows this:
Config flow could not be loaded: Unknown error

Also can you tell me where are the cofig entries I should delete for Deebot 4 Home Assistant

Update: Restarted home assistant and the Ecovacs integration setup worked

**Comment by MVladislav** [comment]
The new core version is failing for me with authenticate for the self hosted bumper version.
It is because of **cert verify failing,** as i use bumper with https.

- For **mqtt** you add an check if the cert should be verified
- The same is **missing** for the **rest** part, to **disable cert verify**
  - Or I miss the point how it works

My current intermediate solution is as follow:

```sh
$docker exec -it homeassistant bash -c "sed -i 's/async_get_clientsession(hass)/async_get_clientsession(hass, verify_ssl=False)/g' /usr/src/homeassistant/homeassistant/components/ecovacs/config_flow.py"
$docker exec -it homeassistant bash -c "sed -i 's/async_get_clientsession(self._hass)/async_get_clientsession(self._hass, verify_ssl=False)/g' /usr/src/homeassistant/homeassistant/components/ecovacs/controller.py"
```

**Comment by mariomaz87** [comment]
Hi, 
I'm planning on migrating but I have one question about point 1: "Remove all Deebot 4 Home Assistant config entries".
What do you mean specifically? I set up the HACS integration using the UI so I don't have created any config entries manually.
Thanks!

**Comment by edenhaus** [comment]
> Hi, I'm planning on migrating but I have one question about point 1: "Remove all Deebot 4 Home Assistant config entries". What do you mean specifically? I set up the HACS integration using the UI so I don't have created any config entries manually. Thanks!

I added a link, which should show all your config entries. You need to remove all first

**Comment by jayscovill** [comment]
I've migrated to the core integration but am having problems with the service call in my automation not working.  I previously used this in my automation, which worked fine with the Deebot HACS integration:


```
service: vacuum.send_command
data:
  params:
    rooms: 0
    cleanings: 1
  command: spot_area
target:
  entity_id: vacuum.george
```


This still seems to work fine if I manually run the action in the automation.  But when it's called from the automation, which is triggered buy a schedule event, it just seems to skip over and exit the automation.

<img width="960" alt="image" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/30603659/28e598f2-b377-4194-a02f-ae469d1637a4">

**Comment by edenhaus** [comment]
@jayscovill Please create an issue in the core repo with the automation traces and logs

**Comment by aidbish** [comment]
I have migrated to the core integration, but it seems it no longer has the command to refresh, will this be added at a later date?

**Comment by edenhaus** [comment]
> I have migrated to the core integration, but it seems it no longer has the command to refresh, will this be added at a later date?

Nope as also in this integration that command is deprecated. Please use the builtin [`update_entity`](https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantupdate_entity) service

**Comment by Stopka** [comment]
I have migrated to the core integration and nowI am missing the last_cleaning sensor. Especially I used it's timestamp attribute in my automations to check if cleaning was already done today.
Why is it missing? Or is there other way to get this value?

**Comment by myhomeiot** [comment]
Also missing way to get last_cleaning, meanwhile I make this by saving time at input_text but sure this was a good sensor in previous version.

**Comment by jayscovill** [comment]
I've never had a last cleaning sensor for the X1 Omni and I've done the same thing.  As part of the cleaning automation I write the current date/time to a input_datetime.

```
service: input_datetime.set_datetime
target:
  entity_id: input_datetime.vacuum_cleaning_start
data:
  datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
```

**Comment by ianackerley** [comment]
I feel like I'm missing something really obvious here (sorry) but without the cleaning_job event what's the best way to monitor for successful completion of a job?

**Comment by edenhaus** [comment]
> I have migrated to the core integration and nowI am missing the last_cleaning sensor. Especially I used it's timestamp attribute in my automations to check if cleaning was already done today.
> Why is it missing? Or is there other way to get this value?

You can use the state of the vacuum itself.  You can use it like in the comment above or you can extract the value with https://www.home-assistant.io/integrations/history_stats/

The last cleaning sensor was not migrated as all information are already available from other sensors

**Comment by edenhaus** [comment]
> I feel like I'm missing something really obvious here (sorry) but without the cleaning_job event what's the best way to monitor for successful completion of a job?

Good point I completely forgot about this event. Sorry. Will check with the core team, if there is a better solution as firing the event

**Comment by smarthomesydney** [comment]
Hi @edenhaus 
Sorry to see you merge.  Have used your integration for years.  Thank you

Quick Q
Without the custom_command, how do I call only specific rooms to be cleaned, based on the room number in the entity info?

**Comment by Stopka** [comment]
Ok, I found solution that serves me well. I created event-triggered template sensor that holds the needed information for me:
```yaml
template:
  - trigger:
      - platform: state
        entity_id: 
          - vacuum.r2d2
        to: 
          - cleaning
    sensor:
      - name: R2D2 Last cleaning time
        state: "{{ now() }}"
        device_class: timestamp
        icon: 'mdi:clock' 
```
Thanks for help, we can close the issue...

**Comment by Stopka** [comment]
> I have migrated to the core integration and nowI am missing the last_cleaning sensor. Especially I used it's timestamp attribute in my automations to check if cleaning was already done today. Why is it missing? Or is there other way to get this value?

Ok, I found solution that serves me well. I created event-triggered template sensor that holds the needed information for me:
```yaml
template:
  - trigger:
      - platform: state
        entity_id: 
          - vacuum.r2d2
        to: 
          - cleaning
    sensor:
      - name: R2D2 Last cleaning time
        state: "{{ now() }}"
        device_class: timestamp
        icon: 'mdi:clock' 
```
