### ISSUE TITLE
Getting Autoempty status after migration

### ISSUE THREAD

**Issue by arifroni** [DeebotUniverse/Deebot-4-Home-Assistant#525]
### Question

I used to have this sensor to check the status of the auto empty.

```
  - trigger:
      - platform: event
        event_type: deebot_custom_command
    sensor:
      - name: deebot_auto_empty
        state: "{{ trigger.event.data.response.body.data.enable }}"
```
It doesn't work anymore. Is there any alternative method to use or am I doing wrong now?
